--
-- create profiles
--

BEGIN
  EXECUTE IMMEDIATE
    'CREATE PROFILE PROF_APPL_UNLIMITED
      limit
      IDLE_TIME 60
      PASSWORD_LIFE_TIME UNLIMITED
      FAILED_LOGIN_ATTEMPTS 5
      PASSWORD_LOCK_TIME 1
      PASSWORD_GRACE_TIME 7
      PASSWORD_REUSE_MAX 12
      PASSWORD_REUSE_TIME UNLIMITED
      PASSWORD_VERIFY_FUNCTION CS_PWD_VERIFY';
EXCEPTION
  WHEN OTHERS THEN
    IF sqlcode != -2379 THEN RAISE;
    END IF;
END;
/
