SELECT
  role
FROM
  dba_roles
WHERE
  role like upper('&1')
  -- mimo DEFAULT ROLE
  AND role NOT IN ( 'CONNECT', 'RESOURCE', 'DBA', 'AUDIT_ADMIN',
    'AUDIT_VIEWER', 'SELECT_CATALOG_ROLE', 'EXECUTE_CATALOG_ROLE',
    'DELETE_CATALOG_ROLE', 'CAPTURE_ADMIN', 'EXP_FULL_DATABASE',
    'IMP_FULL_DATABASE', 'CDB_DBA', 'PDB_DBA', 'LOGSTDBY_ADMINISTRATOR',
    'DBFS_ROLE', 'GSMUSER_ROLE', 'AQ_ADMINISTRATOR_ROLE', 'AQ_USER_ROLE',
    'DATAPUMP_EXP_FULL_DATABASE', 'DATAPUMP_IMP_FULL_DATABASE',
    'ADM_PARALLEL_EXECUTE_TASK', 'PROVISIONER', 'XS_RESOURCE',
    'XS_SESSION_ADMIN', 'XS_NAMESPACE_ADMIN', 'XS_CACHE_ADMIN',
    'GATHER_SYSTEM_STATISTICS', 'OPTIMIZER_PROCESSING_RATE',
    'RECOVERY_CATALOG_OWNER', 'RECOVERY_CATALOG_USER', 'EM_EXPRESS_BASIC',
    'EM_EXPRESS_ALL', 'SCHEDULER_ADMIN', 'HS_ADMIN_SELECT_ROLE',
    'HS_ADMIN_EXECUTE_ROLE', 'HS_ADMIN_ROLE', 'GLOBAL_AQ_USER_ROLE',
    'OEM_ADVISOR', 'OEM_MONITOR', 'XDBADMIN', 'XDB_SET_INVOKER',
    'AUTHENTICATEDUSER', 'XDB_WEBSERVICES', 'XDB_WEBSERVICES_WITH_PUBLIC',
    'XDB_WEBSERVICES_OVER_HTTP', 'GSMADMIN_ROLE', 'GSM_POOLADMIN_ROLE',
    'GDS_CATALOG_SELECT', 'WM_ADMIN_ROLE', 'JAVAUSERPRIV', 'JAVAIDPRIV',
    'JAVASYSPRIV', 'JAVADEBUGPRIV', 'EJBCLIENT', 'JMXSERVER', 'JAVA_ADMIN',
    'JAVA_DEPLOY' )
ORDER BY role;

/*
--
-- SYS
-- prevent ORA-28031: maximum of 148 enabled roles exceeded
--
BEGIN
FOR rec IN (
    select granted_role from dba_role_privs
      where grantee = 'SYS'
        and granted_role not in ('DBA')
           )
LOOP
  execute immediate 'REVOKE '||rec.granted_role||' FROM SYS';
END LOOP;
END;
/

*/