-- Show Status of Supplemental Logging
SET LINES 1000
SET PAGES 1000
COLUMN SL_MIN FORMAT A6
COLUMN SL_PK FORMAT A5
COLUMN SL_UI FORMAT A5
COLUMN SL_FK FORMAT A5
COLUMN SL_ALL FORMAT A6
COLUMN COLUMN_NAME FORMAT A50

SELECT NAME, LOG_MODE, SUPPLEMENTAL_LOG_DATA_MIN SL_MIN, SUPPLEMENTAL_LOG_DATA_PK SL_PK, SUPPLEMENTAL_LOG_DATA_UI SL_UI, SUPPLEMENTAL_LOG_DATA_FK SL_FK, SUPPLEMENTAL_LOG_DATA_ALL SL_ALL FROM V$DATABASE;

SELECT * FROM DBA_LOG_GROUPS where owner != 'SYS' ORDER BY LOG_GROUP_NAME;

SELECT OWNER, LOG_GROUP_NAME, TABLE_NAME, POSITION, LOGGING_PROPERTY, COLUMN_NAME 
  FROM DBA_LOG_GROUP_COLUMNS 
 where owner != 'SYS'
  ORDER BY OWNER, LOG_GROUP_NAME, TABLE_NAME, POSITION;
