#!/bin/sh
. ./helper_functions.sh

structure=$1
db_file=$2

if [ -f "$db_file" ]; then
  $ECHO CONNECTION_METHOD,ORACLE_HOME_SERVER,ORACLE_SID,OS_USER,TNS_NAME,TNS_HOST,TNS_PORT,TNS_SERVICE_NAME,TNS_SID,DB_USER,SQL >$db_file
fi 

if [ "$structure" = "db" ]; then
  if [ "$LMSCT_CONNECTION_METHOD" != "" ];then
	$ECHO $LMSCT_CONNECTION_METHOD,$LMSCT_ORACLE_HOME_SERVER,$LMSCT_ORACLE_SID,$LMSCT_OS_USER,$LMSCT_TNS_NAME,$LMSCT_TNS_HOST,$LMSCT_TNS_PORT,$LMSCT_TNS_SERVICE_NAME,$LMSCT_TNS_SID,$LMSCT_DB_USER,$LMSCT_SQL,$LMSCT_PROMPT_TEXT >>$db_file
  fi
fi

