--
-- GRANTS
--

-- Java privs - bude nutno specificky grantovat pro dané prostředí


WHENEVER SQLERROR CONTINUE

-- system grants
GRANT ADMINISTER ANY SQL TUNING SET to MCI_DB_DEVELOPER;
GRANT ALTER ANY CLUSTER to MCI_DB_DEVELOPER;
GRANT ALTER ANY EVALUATION CONTEXT to MCI_DB_DEVELOPER;
GRANT ALTER ANY INDEX to MCI_DB_DEVELOPER;
GRANT ALTER ANY INDEXTYPE to MCI_DB_DEVELOPER;
GRANT ALTER ANY LIBRARY to MCI_DB_DEVELOPER;
GRANT ALTER ANY MATERIALIZED VIEW to MCI_DB_DEVELOPER;
GRANT ALTER ANY OPERATOR to MCI_DB_DEVELOPER;
GRANT ALTER ANY PROCEDURE to MCI_DB_DEVELOPER;
GRANT ALTER ANY ROLE to MCI_DB_DEVELOPER;
GRANT ALTER ANY RULE SET to MCI_DB_DEVELOPER;
GRANT ALTER ANY RULE to MCI_DB_DEVELOPER;
GRANT ALTER ANY SEQUENCE to MCI_DB_DEVELOPER;
GRANT ALTER ANY SQL PROFILE to MCI_DB_DEVELOPER;
GRANT ALTER ANY TABLE to MCI_DB_DEVELOPER;
GRANT ALTER ANY TRIGGER to MCI_DB_DEVELOPER;
GRANT ALTER ANY TYPE to MCI_DB_DEVELOPER;
GRANT ALTER SESSION to MW_CONNECT;
GRANT ANALYZE ANY to MCI_DB_DEVELOPER;
GRANT ANALYZE ANY to MW_AUDIT;
GRANT ANALYZE ANY to MW_LOG;
GRANT BACKUP ANY TABLE to MCI_DB_DEVELOPER;
GRANT COMMENT ANY TABLE to MCI_DB_DEVELOPER;
GRANT CREATE ANY CLUSTER to MCI_DB_DEVELOPER;
GRANT CREATE ANY CONTEXT to MCI_DB_DEVELOPER;
GRANT CREATE ANY CREDENTIAL to MCI_DB_DEVELOPER;
GRANT CREATE ANY DIRECTORY to MCI_DB_DEVELOPER;
GRANT CREATE ANY EVALUATION CONTEXT to MCI_DB_DEVELOPER;
GRANT CREATE ANY INDEX to MCI_DB_DEVELOPER;
GRANT CREATE ANY INDEXTYPE to MCI_DB_DEVELOPER;
GRANT CREATE ANY JOB to MCI_DB_DEVELOPER;
GRANT CREATE ANY LIBRARY to MCI_DB_DEVELOPER;
GRANT CREATE ANY MATERIALIZED VIEW to MCI_DB_DEVELOPER;
GRANT CREATE ANY OPERATOR to MCI_DB_DEVELOPER;
GRANT CREATE ANY PROCEDURE to MCI_DB_DEVELOPER;
GRANT CREATE ANY RULE SET to MCI_DB_DEVELOPER;
GRANT CREATE ANY RULE to MCI_DB_DEVELOPER;
GRANT CREATE ANY SEQUENCE to MCI_DB_DEVELOPER;
GRANT CREATE ANY SQL PROFILE to MCI_DB_DEVELOPER;
GRANT CREATE ANY SYNONYM to MCI_DB_DEVELOPER;
GRANT CREATE ANY TABLE to MCI_DB_DEVELOPER;
GRANT CREATE ANY TRIGGER to MCI_DB_DEVELOPER;
GRANT CREATE ANY TYPE to MCI_DB_DEVELOPER;
GRANT CREATE ANY VIEW to MCI_DB_DEVELOPER;
GRANT CREATE CREDENTIAL to MW;
GRANT CREATE JOB to MW;
GRANT CREATE PROCEDURE to MW_DB_SERVER;
GRANT CREATE PUBLIC SYNONYM to MW_DB_SERVER;
GRANT CREATE SEQUENCE to MW_DB_SERVER;
GRANT CREATE SESSION to MWSTAT;
GRANT CREATE SESSION to MW_CONNECT;
GRANT CREATE SYNONYM to MWAPP;
GRANT CREATE TABLE to MW;
GRANT CREATE TABLE to MWSTAT;
GRANT CREATE TABLE to MW_DB_SERVER;
GRANT CREATE TRIGGER to MW_DB_SERVER;
GRANT CREATE VIEW to MW_DB_SERVER;
GRANT CSCONNECT to MWSTAT;
GRANT CS_APPL_ACCOUNTS to MW;
GRANT CS_APPL_ACCOUNTS to MWAPP;
GRANT CS_APPL_ACCOUNTS to MWSTAT;
GRANT DEBUG ANY PROCEDURE to MCI_DB_DEVELOPER;
GRANT DELETE ANY TABLE to MCI_DB_DEVELOPER;
GRANT DROP ANY CLUSTER to MCI_DB_DEVELOPER;
GRANT DROP ANY CONTEXT to MCI_DB_DEVELOPER;
GRANT DROP ANY DIRECTORY to MCI_DB_DEVELOPER;
GRANT DROP ANY EVALUATION CONTEXT to MCI_DB_DEVELOPER;
GRANT DROP ANY INDEX to MCI_DB_DEVELOPER;
GRANT DROP ANY INDEXTYPE to MCI_DB_DEVELOPER;
GRANT DROP ANY LIBRARY to MCI_DB_DEVELOPER;
GRANT DROP ANY MATERIALIZED VIEW to MCI_DB_DEVELOPER;
GRANT DROP ANY OPERATOR to MCI_DB_DEVELOPER;
GRANT DROP ANY PROCEDURE to MCI_DB_DEVELOPER;
GRANT DROP ANY ROLE to MCI_DB_DEVELOPER;
GRANT DROP ANY RULE SET to MCI_DB_DEVELOPER;
GRANT DROP ANY RULE to MCI_DB_DEVELOPER;
GRANT DROP ANY SEQUENCE to MCI_DB_DEVELOPER;
GRANT DROP ANY SQL PROFILE to MCI_DB_DEVELOPER;
GRANT DROP ANY SYNONYM to MCI_DB_DEVELOPER;
GRANT DROP ANY TABLE to MCI_DB_DEVELOPER;
GRANT DROP ANY TRIGGER to MCI_DB_DEVELOPER;
GRANT DROP ANY TYPE to MCI_DB_DEVELOPER;
GRANT DROP ANY VIEW to MCI_DB_DEVELOPER;
GRANT ENQUEUE ANY QUEUE to MCI_DB_DEVELOPER;
GRANT EXECUTE ANY CLASS to MCI_DB_DEVELOPER;
GRANT EXECUTE ANY EVALUATION CONTEXT to MCI_DB_DEVELOPER;
GRANT EXECUTE ANY INDEXTYPE to MCI_DB_DEVELOPER;
GRANT EXECUTE ANY LIBRARY to MCI_DB_DEVELOPER;
GRANT EXECUTE ANY OPERATOR to MCI_DB_DEVELOPER;
GRANT EXECUTE ANY PROCEDURE to MCI_DB_DEVELOPER;
GRANT EXECUTE ANY PROGRAM to MCI_DB_DEVELOPER;
GRANT EXECUTE ANY RULE SET to MCI_DB_DEVELOPER;
GRANT EXECUTE ANY RULE to MCI_DB_DEVELOPER;
GRANT EXECUTE ANY TYPE to MCI_DB_DEVELOPER;
GRANT FLASHBACK ANY TABLE to MCI_DB_DEVELOPER;
GRANT FORCE ANY TRANSACTION to MCI_DB_DEVELOPER;
GRANT GRANT ANY OBJECT PRIVILEGE to MCI_DB_DEVELOPER;
GRANT GRANT ANY PRIVILEGE to MCI_DB_DEVELOPER;
GRANT GRANT ANY ROLE to MCI_DB_DEVELOPER;
GRANT INSERT ANY TABLE to MCI_DB_DEVELOPER;
GRANT JAVASYSPRIV to MW;
GRANT LOCK ANY TABLE to MCI_DB_DEVELOPER;
GRANT LOGMINING to MCI_DB_DEVELOPER;
GRANT MANAGE ANY QUEUE to MCI_DB_DEVELOPER;
GRANT MERGE ANY VIEW to MCI_DB_DEVELOPER;
GRANT MW_CONNECT to MW;
GRANT MW_CONNECT to MWAPP;
GRANT MW_DB_SERVER to MW;
GRANT MW_LOG to MWAPP;
GRANT MW_READ_ONLY to MWAPP;
GRANT SELECT ANY DICTIONARY to MCI_DB_DEVELOPER;
GRANT SELECT ANY SEQUENCE to MCI_DB_DEVELOPER;
GRANT SELECT ANY TABLE to MCI_DB_DEVELOPER;
GRANT SELECT ANY TRANSACTION to MCI_DB_DEVELOPER;
GRANT UNDER ANY TABLE to MCI_DB_DEVELOPER;
GRANT UNDER ANY TYPE to MCI_DB_DEVELOPER;
GRANT UNDER ANY VIEW to MCI_DB_DEVELOPER;
GRANT UPDATE ANY TABLE to MCI_DB_DEVELOPER;


-- SYS Grants
GRANT EXECUTE ON "SYS"."DBMS_LOCK" to MW ;
GRANT EXECUTE ON "SYS"."DBMS_SCHEDULER" to MW ;
GRANT READ ON DIRECTORY "SYS"."MW_CSOPS_EXP" to MW ;
GRANT READ ON DIRECTORY "SYS"."MW_DB_LOG" to MW ;
GRANT WRITE ON DIRECTORY "SYS"."MW_CSOPS_EXP" to MW ;
GRANT WRITE ON DIRECTORY "SYS"."MW_DB_LOG" to MW ;
GRANT SELECT ON "SYS"."DBA_PENDING_TRANSACTIONS" to MWAPP ;
