--
-- GRANTS
--

GRANT ANALYZE ANY to DBEIM;
GRANT CREATE JOB to DBEIM;
GRANT CS_APPL_ACCOUNTS to DBEIM;
GRANT DBEIM_READ_ONLY to DBEIM;
GRANT MW_CONNECT to DBEIM;
GRANT MW_DB_SERVER to DBEIM;
GRANT MW_DEBUG to DBEIM;
GRANT ALTER ANY INDEX to DBMAIN;
GRANT ANALYZE ANY to DBMAIN;
GRANT CREATE JOB to DBMAIN;
GRANT CS_APPL_ACCOUNTS to DBMAIN;
GRANT DBEIM_READ_ONLY to DBMAIN;
GRANT DBMAIN_READ_ONLY to DBMAIN;
GRANT MW_CONNECT to DBMAIN;
GRANT MW_DB_SERVER to DBMAIN;
GRANT MW_DEBUG to DBMAIN;
GRANT CREATE DATABASE LINK to MW;
GRANT CREATE JOB to MW;
GRANT CREATE TABLE to MW;
GRANT CS_APPL_ACCOUNTS to MW;
GRANT JAVASYSPRIV to MW;
GRANT MW_CONNECT to MW;
GRANT MW_DB_SERVER to MW;
GRANT CREATE SYNONYM to MWAPP;
GRANT CS_APPL_ACCOUNTS to MWAPP;
GRANT MW_CONNECT to MWAPP;
GRANT MW_LOG to MWAPP;
GRANT MW_READ_ONLY to MWAPP;
GRANT CREATE SESSION to MWSTAT;
GRANT CREATE TABLE to MWSTAT;
GRANT CSCONNECT to MWSTAT;
GRANT CS_APPL_ACCOUNTS to MWSTAT;
GRANT ANALYZE ANY to MW_AUDIT;
GRANT ALTER SESSION to MW_CONNECT;
GRANT CREATE SESSION to MW_CONNECT;
GRANT CREATE MATERIALIZED VIEW to MW_DB_SERVER;
GRANT CREATE PROCEDURE to MW_DB_SERVER;
GRANT CREATE PUBLIC SYNONYM to MW_DB_SERVER;
GRANT CREATE SEQUENCE to MW_DB_SERVER;
GRANT CREATE TABLE to MW_DB_SERVER;
GRANT CREATE TRIGGER to MW_DB_SERVER;
GRANT CREATE TYPE to MW_DB_SERVER;
GRANT CREATE VIEW to MW_DB_SERVER;
GRANT ALTER ANY PROCEDURE to MW_DEBUG;
GRANT DEBUG ANY PROCEDURE to MW_DEBUG;
GRANT DEBUG CONNECT SESSION to MW_DEBUG;
GRANT EXECUTE ANY PROCEDURE to MW_DEBUG;
GRANT EXECUTE ANY TYPE to MW_DEBUG;
GRANT ANALYZE ANY to MW_LOG;

