--
-- GRANTS
--

-- Java privs - bude nutno specificky grantovat pro dané prostředí


WHENEVER SQLERROR CONTINUE

-- system grants
GRANT ALTER SESSION to MW_CONNECT;
GRANT ANALYZE ANY to MW_AUDIT;
GRANT ANALYZE ANY to MW_LOG;
GRANT CREATE CREDENTIAL to MW;
GRANT CREATE JOB to MW;
GRANT CREATE PROCEDURE to MW_DB_SERVER;
GRANT CREATE PUBLIC SYNONYM to MW_DB_SERVER;
GRANT CREATE SEQUENCE to MW_DB_SERVER;
GRANT CREATE SESSION to MWSTAT;
GRANT CREATE SESSION to MW_CONNECT;
GRANT CREATE SYNONYM to MWAPP;
GRANT CREATE TABLE to MW;
GRANT CREATE TABLE to MWSTAT;
GRANT CREATE TABLE to MW_DB_SERVER;
GRANT CREATE TRIGGER to MW_DB_SERVER;
GRANT CREATE VIEW to MW_DB_SERVER;
GRANT CSCONNECT to MWSTAT;
GRANT CS_APPL_ACCOUNTS to MW;
GRANT CS_APPL_ACCOUNTS to MWAPP;
GRANT CS_APPL_ACCOUNTS to MWSTAT;
GRANT JAVASYSPRIV to MW;
GRANT MW_CONNECT to MW;
GRANT MW_CONNECT to MWAPP;
GRANT MW_DB_SERVER to MW;
GRANT MW_LOG to MWAPP;
GRANT MW_READ_ONLY to MWAPP;

-- DBMAIN, DBEIM
GRANT ALTER ANY INDEX to DBMAIN;
GRANT ANALYZE ANY to DBEIM;
GRANT ANALYZE ANY to DBMAIN;
GRANT CREATE CREDENTIAL to DBEIM;
GRANT CREATE CREDENTIAL to DBMAIN;
GRANT CREATE JOB to DBEIM;
GRANT CREATE JOB to DBMAIN;
GRANT DBEIM_READ_ONLY to DBMAIN;
GRANT DBMAIN_READ_ONLY to DBMAIN;
GRANT MW_CONNECT to DBEIM;
GRANT MW_CONNECT to DBMAIN;
GRANT MW_DB_SERVER to DBEIM;
GRANT MW_DB_SERVER to DBMAIN;
GRANT MW_DEBUG to DBEIM;

grant CREATE MATERIALIZED VIEW to DBMAIN;
grant CREATE PROCEDURE to DBMAIN;
grant CREATE PUBLIC SYNONYM to DBMAIN;
grant CREATE SEQUENCE to DBMAIN;
grant CREATE TABLE to DBMAIN;
grant CREATE TRIGGER to DBMAIN;
grant CREATE TYPE to DBMAIN;
grant CREATE VIEW to DBMAIN;

grant CREATE MATERIALIZED VIEW to DBEIM;
grant CREATE PROCEDURE to DBEIM;
grant CREATE PUBLIC SYNONYM to DBEIM;
grant CREATE SEQUENCE to DBEIM;
grant CREATE TABLE to DBEIM;
grant CREATE TRIGGER to DBEIM;
grant CREATE TYPE to DBEIM;
grant CREATE VIEW to DBEIM;


-- SYS Grants
GRANT EXECUTE ON "SYS"."DBMS_LOCK" to MW ;
GRANT EXECUTE ON "SYS"."DBMS_SCHEDULER" to MW ;
GRANT READ ON DIRECTORY "SYS"."MW_CSOPS_EXP" to MW ;
GRANT READ ON DIRECTORY "SYS"."MW_DB_LOG" to MW ;
GRANT WRITE ON DIRECTORY "SYS"."MW_CSOPS_EXP" to MW ;
GRANT WRITE ON DIRECTORY "SYS"."MW_DB_LOG" to MW ;
GRANT SELECT ON "SYS"."DBA_PENDING_TRANSACTIONS" to MWAPP ;
