--
-- Databazove profily
-- verze NON PCI DSS
--
-- Changes:
--   17.5.2017 - navyseni limitu SESSIONS_PER_USER na 8 dle platne bezp. dokumentace
--

CREATE PROFILE "PROF_DBA" limit
IDLE_TIME 60
FAILED_LOGIN_ATTEMPTS 5 PASSWORD_LOCK_TIME 15/1440
PASSWORD_GRACE_TIME 20 PASSWORD_LIFE_TIME 80
PASSWORD_REUSE_MAX 12 PASSWORD_REUSE_TIME UNLIMITED
PASSWORD_VERIFY_FUNCTION CS_PWD_VERIFY;

CREATE PROFILE "PROF_USER" limit
IDLE_TIME 60 SESSIONS_PER_USER 8
FAILED_LOGIN_ATTEMPTS 5 PASSWORD_LOCK_TIME 15/1440
PASSWORD_GRACE_TIME 7 PASSWORD_LIFE_TIME 23
PASSWORD_REUSE_MAX 12 PASSWORD_REUSE_TIME UNLIMITED
PASSWORD_VERIFY_FUNCTION CS_PWD_VERIFY;

CREATE PROFILE "PROF_APPL" limit
IDLE_TIME 60
FAILED_LOGIN_ATTEMPTS 5 PASSWORD_LOCK_TIME 1
PASSWORD_GRACE_TIME 7 PASSWORD_LIFE_TIME 413
PASSWORD_REUSE_MAX 12 PASSWORD_REUSE_TIME UNLIMITED
PASSWORD_VERIFY_FUNCTION CS_PWD_VERIFY;

CREATE PROFILE "PROF_ADHOC"
LIMIT CPU_PER_SESSION
DEFAULT CPU_PER_CALL DEFAULT
CONNECT_TIME 480 IDLE_TIME
30 SESSIONS_PER_USER 8
LOGICAL_READS_PER_SESSION
DEFAULT LOGICAL_READS_PER_CALL
DEFAULT PRIVATE_SGA DEFAULT
COMPOSITE_LIMIT DEFAULT
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME 15/1440
PASSWORD_GRACE_TIME 7
PASSWORD_LIFE_TIME 23
PASSWORD_REUSE_MAX 12
PASSWORD_REUSE_TIME UNLIMITED
PASSWORD_VERIFY_FUNCTION
CS_PWD_VERIFY;


CREATE PROFILE "PROF_SUPP"
limit
IDLE_TIME 60
SESSIONS_PER_USER 8
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME 15/1440
PASSWORD_GRACE_TIME 7
PASSWORD_LIFE_TIME 23
PASSWORD_REUSE_MAX 12
PASSWORD_REUSE_TIME UNLIMITED
PASSWORD_VERIFY_FUNCTION
CS_PWD_VERIFY;

CREATE PROFILE "PROF_BATCH"
limit
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME 1
PASSWORD_GRACE_TIME 7
PASSWORD_LIFE_TIME 413
PASSWORD_REUSE_MAX 12
PASSWORD_REUSE_TIME UNLIMITED
PASSWORD_VERIFY_FUNCTION
CS_PWD_VERIFY;




REM List changed values
REM ===================
col PROFILE for a15
col LIMIT   for a15
set pages 1000 feed off
prompt created profiles;
prompt ----------------;
SELECT UNIQUE (PROFILE) FROM dba_profiles order by 1;
prompt;
prompt profile non default values;
prompt --------------------------;
SELECT PROFILE, resource_name, LIMIT FROM dba_profiles where limit!='DEFAULT'
and profile != 'DEFAULT' ORDER BY 1, 2, 3;

