GRANT SELECT ON SYS.V_$DATABASE TO &&role;
GRANT SELECT ON SYS.V_$INSTANCE TO &&role;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO &&role;
GRANT SELECT ON SYS.DBA_HIST_DATABASE_INSTANCE TO &&role;
GRANT SELECT ON SYS.DBA_HIST_SNAPSHOT TO &&role;