REM INSERTING into DB_CONTACTS
SET DEFINE OFF;
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('8','RDS','Jana Legnerová <jlegnerova@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('119','AFS','Petr Roučka <proucka@csas.cz>, Zdeněk Elis <zelis@csas.cz>, Aleš Zíka <azika@csas.cz>, CEN 7320_02 IT podpora scoringových aplikací TEAM <it_scoring@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('1','AML','Petr Roučka <proucka@csas.cz>, Zdeněk Elis <zelis@csas.cz>, Aleš Zíka <azika@csas.cz>, CEN 7320_02 IT podpora scoringových aplikací TEAM <it_scoring@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('3','APS','Petr Roučka <proucka@csas.cz>, Zdeněk Elis <zelis@csas.cz>, Aleš Zíka <azika@csas.cz>, CEN 7320_02 IT podpora scoringových aplikací TEAM <it_scoring@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('6','BESC','Petr Roučka <proucka@csas.cz>, Zdeněk Elis <zelis@csas.cz>, Aleš Zíka <azika@csas.cz>, CEN 7320_02 IT podpora scoringových aplikací TEAM <it_scoring@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('114','CASE','Jiří Macich <jmacich@csas.cz>, AS Frontend - Distribuce TEAM <fas-omega@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('11','CCDB','Jan Marek <jmarek@csas.cz>, "Milan Milták (Controlling)" <mmiltak@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('104','CMT','Milan Douda <mdouda@csas.cz>, "CEN 8650_01, IT vývoj DMS-Infrastructure" <CEN8650_01ITvyvojDMS-Infrastructure@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('16','COGNO','Stanislav Adámek <sadamek@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('103','COLMAN','Roman Varadi <rvaradi@csas.cz>, Zdík Kudrle <zkudrle@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('48','CSEXT','Šilha Jaroslav <JSilha@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('116','CSINT','Šilha Jaroslav <JSilha@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('29','DMX','Milan Douda <mdouda@csas.cz>, "CEN 8650_01, IT vývoj DMS-Infrastructure" <CEN8650_01ITvyvojDMS-Infrastructure@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('22','ECRS','Milan Douda <mdouda@csas.cz>, "CEN 8650_01, IT vývoj DMS-Infrastructure" <CEN8650_01ITvyvojDMS-Infrastructure@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('42','FASCR','Pavel Jecha <PJecha@csas.cz>, Petr Roučka <proucka@csas.cz>, CEN 7320_02 IT podpora scoringových aplikací TEAM <it_scoring@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('100','HYPERION','Helena Hrdinová <hhrdinova@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('105','INF_MNG FREE',null);
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('118','KNPROXY','Petr Roučka <proucka@csas.cz>, Zdeněk Elis <zelis@csas.cz>, Aleš Zíka <azika@csas.cz>, CEN 7320_02 IT podpora scoringových aplikací TEAM <it_scoring@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('55','MAT','Tomáš Gurka <tgurka@csas.cz>, CEN 8620_02 Aplikační podpora - MAT <matsupport@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('12','MCI','Tomáš Jeníček <tjenicek@ext.csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('112','MEP','Roman Sebránek <rsebranek@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('71','P24','Marek Lévy <mlevy@csas.cz>, Michael Braun <mbraun@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('64','PDBA','Tomáš Roubal <troubal@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('93','VSUD','Stanislav Adámek <sadamek@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('223','WBL','Igor Fusek <IFusek@csas.cz>');
Insert into DB_CONTACTS (APP_ID,APP_NAME,DB_CONTACT) values ('94','WCM','Šilha Jaroslav <JSilha@csas.cz>');
