--
-- DWH pre tasks
--

-- granty
grant ADMINISTER DATABASE TRIGGER to DWH_OWNER;

-- DWH OWNER disable cons
BEGIN
  for rec in (
    SELECT
        c.owner,
        tc.table_name,
        c.constraint_name
    FROM
             dba_constraints c
        JOIN dba_cons_columns cc ON c.constraint_name = cc.constraint_name
        JOIN dba_tab_columns tc ON tc.column_name = cc.column_name
                                   AND tc.table_name = cc.table_name
    WHERE
        c.owner = 'DWH_OWNER'
        AND c.table_name IN (
            'DEPOSIT_ACCOUNT_HISTORY',
            'ACCOUNT_HISTORY',
            'CARD_HISTORY'
        )
        AND cc.column_name in (
          'HDGTP_KEY', 'TBOOK_KEY', 'CARDH_BONUS_PROGRAM_FLAG','ACCH_CHANGE_DATE','ACCH_CHANGE_DATE',
          'ACCH_CR_PERIODS_COUNT', 'ACCH_DR_PERIODS_COUNT', 'ACCH_DR_IR_CHANGE_DATE', 'ACCH_DR_PERIOD_TYPE',
          'ACCH_AGREE_REPAY_END_DATE',
          'ACCH_SEQ', 'ACCH_SOURCE_SYSTEM_ID', 'ACCH_PAYMENT_FIRST_CONTR_DATE', 'ACCH_LIMIT_AMOUNT', 'ACCH_NOMINAL_AMOUNT', 'ACCH_AGREED_PAYMENT_FREQ', 'ACCH_AGREED_PAYMENT_METHOD', 'ACCH_AGREED_MATURITY_DATE', 'ACCH_WITHDRAW_FIRST_PERM_DATE', 'ACCH_WITHDRAW_FIRST_DATE', 'ACCH_PAYMENT_LAST_CONTR_DATE', 'ACCH_PAYMENT_FIRST_DATE', 'ACCH_RESTRUCTURING_DATE', 'ACCH_OVERDRAFT_FLAG', 'ACCH_OVERDRAFT_OPEN_DATE', 'ACCH_OVERDRAFT_CLOSE_DATE', 'ACCH_OVERDRAFT_FIRST_DATE', 'ACCH_OVERDRAFT_LIMIT_TYPE', 'ACCH_OVERDRAFT_LIMIT_AMOUNT', 'ACCH_OVERDRAFT_CYCLE', 'ACCH_SOURCE_ID', 'ACCH_ACCOUNT_PREFIX', 'ACCH_ACCOUNT_NUMBER', 'ACCH_ACCOUNT_SPECIFIC_SYMBOL', 'ACCH_ACCOUNT_FULL_NUMBER', 'ACCH_OPEN_DATE', 'ACCH_APPROVAL_DATE', 'ACCH_CONTRACT_SIGNATURE_DATE', 'ACCH_CLOSE_FLAG', 'ACCH_CLOSE_DATE', 'ACCH_WRITEOFF_FLAG', 'ACCH_WRITEOFF_DATE', 'ACCH_COLLECTIONS_FLAG', 'ACCH_COLLECTIONS_DATE', 'ACCH_TAX_CODE', 'ACCH_VALID_FROM', 'ACCH_VALID_TO', 'ACCH_CURRENT_FLAG', 'ACCH_INSERTED_DATETIME', 'ACCH_UPDATED_DATETIME', 'ACCH_INSERT_PROCESS_KEY', 'ACCH_UPDATE_PROCESS_KEY', 'ACCH_DELETED_FLAG', 'ACCH_INTEREST_ALL_PRINC_FLAG', 'ACCH_REVOLVING_FLAG', 'ACCH_DRAWING_END_DATE', 'ACCH_SYNDICATE_CODE', 'ACCH_CR_IR_CHANGE_DATE', 'ACCH_CR_PERIOD_TYPE', 'ACCH_WRITEOFF_PAID_DATE', 'ACCH_OVERDRAFT_BLOCK_DATE', 'ACCH_PRODUCT_TERM_TYPE', 'ACCH_NOTICE_PERIOD_TYPE', 'ACCH_ARBITRAGE_NUMBER', 'ACCH_TF_PRODUCT_TERM_TYPE', 'ACCH_AGREE_REPAY_START_DATE', 'ACCH_AGREE_REPAY_TOLER_COUNT', 'ACCH_AGREE_REPAY_AUTO_END_FLAG', 'ACCH_CONTRACT_DURATION_CNT'
          )
            AND c.constraint_type = 'C'
            AND c.status = 'ENABLED'
         -- and tc.nullable = 'N'
  ) loop
  execute immediate 'ALTER TABLE '|| rec.owner || '.' || rec.table_name
                    || ' DISABLE CONSTRAINT ' || rec.constraint_name;
  end loop;
END;
/
