CREATE TABLE SYSTEM.LOAD_TABLE(
  	"TABLE_OWNER" VARCHAR2(60 CHAR) NOT NULL ENABLE,
	  "TABLE_NAME" VARCHAR2(60 CHAR) NOT NULL ENABLE,
	  "RUN_ID" NUMBER NOT NULL ENABLE,
	  "LOAD_SQL" CLOB
    );

ALTER TABLE SYSTEM.LOAD_TABLE ADD CONSTRAINT "LOAD_TABLE_PK" PRIMARY KEY ("TABLE_OWNER", "TABLE_NAME", "RUN_ID");


CREATE TABLE SYSTEM.LOAD_TABLE_LOG(
  "LOG_DT" TIMESTAMP (6),
	"LOG_INFO" VARCHAR2(4000 BYTE)
  );
