# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: SQLCheck Action
      uses: yokawasa/action-sqlcheck@1.2.1
      with:
        # Post comment to PR
        post-comment: # optional, default is true
        # Github Token in order to add comment to PR
        token: # default is 
        # Set of SQL anti-patterns to check: 1,2, or 3
        risk-level: # optional, default is 3
        # Add verbose warnings to SQLCheck analysis result
        verbose: # optional
        # List of file postfix to match ( separator: comma )
        postfixes: # optional, default is sql
